// Server sent action types
export type SERVER_DISCONNECT = 'SERVER_DISCONNECT'
export const SERVER_DISCONNECT: SERVER_DISCONNECT = 'SERVER_DISCONNECT'

export type SERVER_MODEL_CHANGED = 'SERVER_MODEL_CHANGED'
export const SERVER_MODEL_CHANGED: SERVER_MODEL_CHANGED = 'SERVER_MODEL_CHANGED'

export type SERVER_HILITE_CHANGED = 'SERVER_HILITE_CHANGED'
export const SERVER_HILITE_CHANGED: SERVER_HILITE_CHANGED =
  'SERVER_HILITE_CHANGED'

export const PAGE_LOADED = 'PAGE_LOADED'
export type PAGE_LOADED = typeof PAGE_LOADED
