// ligand action types
export const LIGAND_TOGGLE_VISIBILITY = 'LIGAND_TOGGLE_VISIBILITY';
export type LIGAND_TOGGLE_VISIBILITY = typeof LIGAND_TOGGLE_VISIBILITY;

// ligands action types
export const LIGANDS_FETCH_REQUESTED = 'LIGANDS_FETCH_REQUESTED';
export type LIGANDS_FETCH_REQUESTED = typeof LIGANDS_FETCH_REQUESTED;

export const LIGANDS_FETCH_SUCCEEDED = 'LIGANDS_FETCH_SUCCEEDED';
export type LIGANDS_FETCH_SUCCEEDED = typeof LIGANDS_FETCH_SUCCEEDED;

export const LIGANDS_SHOW = 'LIGANDS_SHOW';
export type LIGANDS_SHOW = typeof LIGANDS_SHOW;

export const LIGANDS_HIDE = 'LIGANDS_HIDE';
export type LIGANDS_HIDE = typeof LIGANDS_HIDE;

// hilite
export const LIGANDS_HILITE_SHOWN = 'LIGANDS_HILITE_SHOWN';
export type LIGANDS_HILITE_SHOWN = typeof LIGANDS_HILITE_SHOWN;

export const LIGANDS_HILITE_FETCH_REQUESTED = 'LIGANDS_HILITE_FETCH_REQUESTED';
export type LIGANDS_HILITE_FETCH_REQUESTED = typeof LIGANDS_HILITE_FETCH_REQUESTED;

export const LIGANDS_HILITE_FETCH_SUCCEEDED = 'LIGANDS_HILITE_FETCH_SUCCEEDED';
export type LIGANDS_HILITE_FETCH_SUCCEEDED = typeof LIGANDS_HILITE_FETCH_SUCCEEDED;
