language: node_js
node_js: 7
sudo: false
script:
- yarn test -- --coverage
# The linter errors on js used in lcov-report, so remove it before linting
- rm -r coverage/lcov-report
- yarn lint
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
cache: 
- yarn
- directories:
  - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "3d-e-chem"
