language: node_js
node_js: 12
sudo: false
script:
- yarn test -- --coverage --no-cache -w 1
- yarn lint
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
cache: 
- yarn
- directories:
  - $HOME/.sonar/cache
addons:
  sonarcloud:
    organization: "3d-e-chem"
