export const CENTER_STAGE_REQUESTED = 'CENTER_STAGE_REQUESTED'
export type CENTER_STAGE_REQUESTED = typeof CENTER_STAGE_REQUESTED

export const CENTER_STAGE_SUCCEEDED = 'CENTER_STAGE_SUCCEEDED'
export type CENTER_STAGE_SUCCEEDED = typeof CENTER_STAGE_SUCCEEDED
