// protein action types
export type PROTEIN_TOGGLE_VISIBILITY = 'PROTEIN_TOGGLE_VISIBILITY';
export const PROTEIN_TOGGLE_VISIBILITY: PROTEIN_TOGGLE_VISIBILITY = 'PROTEIN_TOGGLE_VISIBILITY';

export type PROTEIN_TOGGLE_HETVISIBILITY = 'PROTEIN_TOGGLE_HETVISIBILITY';
export const PROTEIN_TOGGLE_HETVISIBILITY: PROTEIN_TOGGLE_HETVISIBILITY = 'PROTEIN_TOGGLE_HETVISIBILITY';

export type PROTEIN_TOGGLE_POCKETVISIBILITY = 'PROTEIN_TOGGLE_POCKETVISIBILITY';
export const PROTEIN_TOGGLE_POCKETVISIBILITY: PROTEIN_TOGGLE_POCKETVISIBILITY = 'PROTEIN_TOGGLE_POCKETVISIBILITY';

// proteins action types
export type PROTEINS_FETCH_REQUESTED = 'PROTEINS_FETCH_REQUESTED';
export const PROTEINS_FETCH_REQUESTED: PROTEINS_FETCH_REQUESTED = 'PROTEINS_FETCH_REQUESTED';

export type PROTEINS_FETCH_SUCCEEDED = 'PROTEINS_FETCH_SUCCEEDED';
export const PROTEINS_FETCH_SUCCEEDED: PROTEINS_FETCH_SUCCEEDED = 'PROTEINS_FETCH_SUCCEEDED';

export type PROTEINS_SHOW = 'PROTEINS_SHOW';
export const PROTEINS_SHOW: PROTEINS_SHOW = 'PROTEINS_SHOW';

export type PROTEINS_HIDE = 'PROTEINS_HIDE';
export const PROTEINS_HIDE: PROTEINS_HIDE = 'PROTEINS_HIDE';
