// protein action types
export const PROTEIN_TOGGLE_VISIBILITY = 'PROTEIN_TOGGLE_VISIBILITY';
export type PROTEIN_TOGGLE_VISIBILITY = typeof PROTEIN_TOGGLE_VISIBILITY;

export const PROTEIN_TOGGLE_HETVISIBILITY = 'PROTEIN_TOGGLE_HETVISIBILITY';
export type PROTEIN_TOGGLE_HETVISIBILITY = typeof PROTEIN_TOGGLE_HETVISIBILITY;

export const PROTEIN_TOGGLE_POCKETVISIBILITY = 'PROTEIN_TOGGLE_POCKETVISIBILITY';
export type PROTEIN_TOGGLE_POCKETVISIBILITY = typeof PROTEIN_TOGGLE_POCKETVISIBILITY;

export const PROTEIN_TOGGLE_PROTEINVISIBILITY = 'PROTEIN_TOGGLE_PROTEINVISIBILITY';
export type PROTEIN_TOGGLE_PROTEINVISIBILITY = typeof PROTEIN_TOGGLE_PROTEINVISIBILITY;

// proteins action types
export const PROTEINS_FETCH_REQUESTED = 'PROTEINS_FETCH_REQUESTED';
export type PROTEINS_FETCH_REQUESTED = typeof PROTEINS_FETCH_REQUESTED;

export const PROTEINS_FETCH_SUCCEEDED = 'PROTEINS_FETCH_SUCCEEDED';
export type PROTEINS_FETCH_SUCCEEDED = typeof PROTEINS_FETCH_SUCCEEDED;

export const PROTEINS_SHOW = 'PROTEINS_SHOW';
export type PROTEINS_SHOW = typeof PROTEINS_SHOW;

export const PROTEINS_HIDE = 'PROTEINS_HIDE';
export type PROTEINS_HIDE = typeof PROTEINS_HIDE;
