// pharmacophore action types
export const PHARMACOPHORE_TOGGLE_CONTAINER_VISIBILITY = 'PHARMACOPHORE_TOGGLE_CONTAINER_VISIBILITY';
export type PHARMACOPHORE_TOGGLE_CONTAINER_VISIBILITY = typeof PHARMACOPHORE_TOGGLE_CONTAINER_VISIBILITY;

export const PHARMACOPHORE_TOGGLE_PHARMACOPHORE_VISIBILITY = 'PHARMACOPHORE_TOGGLE_PHARMACOPHORE_VISIBILITY';
export type PHARMACOPHORE_TOGGLE_PHARMACOPHORE_VISIBILITY = typeof PHARMACOPHORE_TOGGLE_PHARMACOPHORE_VISIBILITY;

export const PHARMACOPHORE_TOGGLE_PHARMACOPHORE_OPACITY = 'PHARMACOPHORE_TOGGLE_PHARMACOPHORE_OPACITY';
export type PHARMACOPHORE_TOGGLE_PHARMACOPHORE_OPACITY = typeof PHARMACOPHORE_TOGGLE_PHARMACOPHORE_OPACITY;

export const PHARMACOPHORE_TOGGLE_LIGAND_VISIBILITY = 'PHARMACOPHORE_TOGGLE_LIGAND_VISIBILITY';
export type PHARMACOPHORE_TOGGLE_LIGAND_VISIBILITY = typeof PHARMACOPHORE_TOGGLE_LIGAND_VISIBILITY;

export const PHARMACOPHORE_TOGGLE_PROTEIN_VISIBILITY = 'PHARMACOPHORE_TOGGLE_PROTEIN_VISIBILITY';
export type PHARMACOPHORE_TOGGLE_PROTEIN_VISIBILITY = typeof PHARMACOPHORE_TOGGLE_PROTEIN_VISIBILITY;

export const PHARMACOPHORE_TOGGLE_POCKET_VISIBILITY = 'PHARMACOPHORE_TOGGLE_POCKET_VISIBILITY';
export type PHARMACOPHORE_TOGGLE_POCKET_VISIBILITY = typeof PHARMACOPHORE_TOGGLE_POCKET_VISIBILITY;

// pharmacophores action types
export const PHARMACOPHORES_SHOW = 'PHARMACOPHORES_SHOW';
export type PHARMACOPHORES_SHOW = typeof PHARMACOPHORES_SHOW;

export const PHARMACOPHORES_HIDE = 'PHARMACOPHORES_HIDE';
export type PHARMACOPHORES_HIDE = typeof PHARMACOPHORES_HIDE;

export const PHARMACOPHORES_ADJUST_POCKETRADIUS = 'PHARMACOPHORES_ADJUST_POCKETRADIUS';
export type PHARMACOPHORES_ADJUST_POCKETRADIUS = typeof PHARMACOPHORES_ADJUST_POCKETRADIUS;

export const PHARMACOPHORES_FETCH_REQUESTED = 'PHARMACOPHORES_FETCH_REQUESTED';
export type PHARMACOPHORES_FETCH_REQUESTED = typeof PHARMACOPHORES_FETCH_REQUESTED;

export const PHARMACOPHORES_FETCH_SUCCEEDED = 'PHARMACOPHORES_FETCH_SUCCEEDED';
export type PHARMACOPHORES_FETCH_SUCCEEDED = typeof PHARMACOPHORES_FETCH_SUCCEEDED;

export const PHARMACOPHORES_FETCH_FAILED = 'PHARMACOPHORES_FETCH_FAILED';
export type PHARMACOPHORES_FETCH_FAILED = typeof PHARMACOPHORES_FETCH_FAILED;
